apiVersion: apps/v1
kind: Deployment
metadata:
  name:  share-safe
  namespace: default
  labels:
    app:  share-safe
    component: api
spec:
  selector:
    matchLabels:
      app: share-safe
      component: api
  replicas: 1
  template:
    metadata:
      labels:
        app:  share-safe
        component: api
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  share-safe-api
        image:  satish860/sharesafeapi:1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: DBHOST
            value: mongodb://db:27017
          - name: DBNAME
            value: files
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        ports:
            - containerPort: 80
              name: api
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: share-safe-api
  namespace: default
  labels:
    app: share-safe
    component: api
spec:
  selector:
    app: share-safe
    component: api
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: api

---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: share-safe-ingress
  namespace: default
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  tls:
  - hosts:
    - api.sharesafe.in
    secretName: letsencrypt-nginx
  rules:
   - host: api.sharesafe.in
     http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: share-safe-api
            port:
              number: 80
  ingressClassName: nginx
---