apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo
  namespace: default
  labels:
    app:  share-safe
    component: mongodb
spec:
  selector:
    matchLabels:
      app: share-safe
      component: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app:  share-safe
        component: mongodb
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mongo
        image:  mongo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  27017
          name:  mongo
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
  labels:
    app:  share-safe
    component: mongodb
spec:
  selector:
    app:  share-safe
    component: mongodb
  type: ClusterIP
  ports:
  - name: mongo
    port: 27017
    targetPort: mongo
---